# Generated by Django 2.0.9 on 2020-03-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
